# Location: /home/dev/work/internal-monorepo/libs/my-cool-library/.oss_porter_state.toml
# State file for oss-porter managed project 'my-cool-library'
# Located within the target internal project subdirectory.
# DO NOT MANUALLY EDIT unless necessary to reset sync point.
# COMMIT THIS FILE to the internal repository.

last_synced_internal_commit = "a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0"

    