[workspace]
members = [
    "core",
    "cli",
    # Add flutter bridge crate later if needed directly in workspace
]

[workspace.dependencies]
log = "^0.4"
thiserror = "^1.0"
serde = { version = "^1.0", features = ["derive"] }
toml = "^0.8"